server {
  listen 80;
  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://server:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Tenant $http_x_tenant;
  }

  location /g/ {
    proxy_pass http://server:8080;
    proxy_set_header Host $host;
    # TODO: rate-limit гостевого контура (limit_req_zone вынести в http-контекст)
  }

  location / {
    try_files $uri /index.html;
  }
}
